baseURL = "https://jashidsany.com/"
languageCode = "en-us"
title = "Jashid Sany"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Hey, I'm Jashid"
    Content = "Iâ€™m a security researcher and malware developer diving deep into offensive security, malware development, and Windows internals."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jashidsany"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jashidsany"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "hackthebox"
    name = "HackTheBox"
    url = "/hackthebox/"
    weight = 2
  [[menu.main]]
    identifier = "malwaredev"
    name = "Malware Dev"
    url = "/malware-dev/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
    guessSyntax = true
