baseURL = "https://jashidsany.com/"
languageCode = "en-us"
title = "Jashid Sany"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

  [params.homeInfoParams]
    Title = "Hey, I'm Jashid"
    Content = "I'm a security researcher and malware developer diving deep into offensive security, malware development, and Windows internals."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/jashidsany"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/jashidsany"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
    guessSyntax = true
