baseURL = "https://jashidsany.com/"
languageCode = "en-us"
title = "Jashid Sany"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true
  showShareButtons = false
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/jashidsany"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    codeFences = true
    guessSyntax = true
